version: '3'

services:
  backend:
    restart: unless-stopped
    build: 
      context: asana-back
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
    container_name: backend

  frontend:
    build: 
      context: asana-front
    container_name: frontend
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Benjamin123
      MYSQL_DATABASE: asana
      MYSQL_PASSWORD: Benjamin123
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d